In [28]:
import pandas as pd

In [29]:
df = pd.read_csv("Coded_Data.csv")
df = df.drop('Unnamed: 0',axis=1)
df

     Cd_1  Cd_2  Cd_3  Cd_4  Cd_5  Cd_6  Cd_7  Cd_8  Cd_9  Cd_10 Result
0    53.1  63.4  33.0  46.2  47.3  21.2  44.3  36.1  46.6   65.0      Y
1    36.9  54.7  31.1  50.5  56.0  38.9  39.4  56.8  33.0   78.8      N
2    41.9  65.5  53.5  52.3  92.5  43.2  94.9  64.7  50.8   67.9      N
3    71.7  75.6  37.9  50.5  69.2  52.5  82.3  77.3  80.8   60.9      Y
4    74.3  51.8  36.4  40.9  74.7  42.2  65.1  36.2  77.6   74.9      Y
..    ...   ...   ...   ...   ...   ...   ...   ...   ...    ...    ...
995  58.7  56.4  49.5  38.1  62.8  35.2  43.6  17.9  59.3   71.2      Y
996  33.4  52.1  54.7  48.5  85.7  76.2  61.6  40.0  50.8   87.8      N
997  66.0  53.6  45.4  56.1  54.6  53.1  22.6  21.8  48.8   73.2      Y
998  63.0  47.0  23.6  40.7  97.5  56.6  50.0  59.4  67.7   62.7      Y
999  48.6  52.4  24.2  48.9  56.6  25.5  45.4  50.9  66.7   72.1      Y

[1000 rows x 11 columns]

In [30]:
x = df.drop('Result', axis=1)
y = df[['Result']]

from sklearn.neighbors import KNeighborsClassifier
knn_model = KNeighborsClassifier(n_neighbors=3)
knn_model.fit(x, y)

# final prediction score result 
knn_model.score(x, y)

0.962